### ISSUE TITLE
Phonegap Build Support

### ISSUE THREAD

**Issue by dgutie02** [shaithana/cordova-plugin-wezka-nativecamera#21]
Hey,

  Just writing to see if this new plugin can be submitted to phonegap build. While I do not intend to use this right away (I'd rather let this project mature some more), it will be helpful for when it's ready for production use.

Thanks,
David

**Comment by shaithana** [comment]
I hope in September. Thanks for support.

**Comment by Heshyo** [comment]
It works with the current version, I just had to add a description tag to the plugin.xml file.
